version: '3'

services:
  postgres:
    container_name: postgres-MA
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  nest-backend:
    container_name: backend-MA
    depends_on:
      - postgres
    build: 
      context: ./wasm-server-be/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=192.168.178.35
    ports:
      - "3000:3000"
      - "3001:3001"
      
  next-frontend:
    container_name: frontend-MA
    depends_on:
      - nest-backend
    build: 
      context: ./wasm-cluster-fe/
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_BACKEND=192.168.178.35
    ports:
      - "4000:4000"

volumes:
  postgres_data:
